# Generated by Django 4.1.4 on 2023-01-03 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction_listings',
            name='image_url',
            field=models.URLField(blank=True),
        ),
    ]
