# Generated by Django 4.1.4 on 2023-01-03 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_alter_auction_listings_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction_listings',
            name='current_price',
            field=models.FloatField(default=1),
        ),
        migrations.AlterField(
            model_name='auction_listings',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='auction_listings',
            name='title',
            field=models.CharField(max_length=64, unique=True),
        ),
    ]
