# Generated by Django 4.1.4 on 2023-01-04 03:48

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_alter_auction_listings_current_price_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auction_listings',
            name='wish_list',
        ),
        migrations.AddField(
            model_name='auction_listings',
            name='watchlist',
            field=models.ManyToManyField(blank=True, related_name='watched', to=settings.AUTH_USER_MODEL),
        ),
    ]
