# Generated by Django 4.1.5 on 2023-01-06 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_remove_auction_listings_wish_list_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction_listings',
            name='title',
            field=models.CharField(max_length=64),
        ),
    ]
