# Generated by Django 4.1.5 on 2023-01-06 02:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_alter_auction_listings_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bids',
            name='bid_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='past_bids', to='auctions.auction_listings'),
        ),
    ]
