# Generated by Django 4.1.5 on 2023-01-09 06:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0007_alter_bids_bidder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction_listings',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='selling', to=settings.AUTH_USER_MODEL),
        ),
    ]
