# Generated by Django 4.1.5 on 2023-01-11 05:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0008_alter_auction_listings_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment_section',
            name='post',
        ),
        migrations.AddField(
            model_name='comment_section',
            name='post',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='auctions.auction_listings'),
        ),
    ]
