# Generated by Django 4.1.5 on 2023-01-11 10:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0009_remove_comment_section_post_comment_section_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction_listings',
            name='sold_to',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bougt', to=settings.AUTH_USER_MODEL),
        ),
    ]
